image: mcr.microsoft.com/dotnet/sdk:5.0-alpine

variables:
  BUILD_FOLDER: SimpleTrading.Deposit.GrpcService
  DOCKER_IMAGE_TAG: monfex/simple-trading-deposit-grpc-service
  KUBERNETES_APP_SELECTOR_NAME_DEV: simple-trading-deposit-manager

stages:
  - build
  - publish

build:
  stage: build
  tags: [monfex]
  script:
    - cd ${BUILD_FOLDER}
    - dotnet publish -o app -c release
  artifacts:
    paths:
      - ${BUILD_FOLDER}
  only:
    - test
    - develop
    - master

publish-prod:
  stage: publish
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - cd ${BUILD_FOLDER}
    - projectfile=${BUILD_FOLDER}
    - ver=$(cat $projectfile.csproj | grep '<Version>' | awk -F ">" '{print $2}' | awk -F"<" '{print $1}')
    - echo $ver
    - ls app
    - echo "$DOCKER_LOGIN"
    - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY_HOST --username $DOCKER_LOGIN --password-stdin
    - docker build  --build-arg app_version=${DOCKER_IMAGE_TAG}:$ver --build-arg app_compilation_date=`date -u +"%Y-%m-%dT%H:%M:%SZ"` -t $DOCKER_REGISTRY_HOST/${DOCKER_IMAGE_TAG}:$ver .
    - docker push $DOCKER_REGISTRY_HOST/${DOCKER_IMAGE_TAG}:$ver
  image: docker:latest
  only:
    - master

publish-test:
  stage: publish
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - cd ${BUILD_FOLDER}
    - projectfile=${BUILD_FOLDER}
    - ver=$(cat $projectfile.csproj | grep '<Version>' | awk -F ">" '{print $2}' | awk -F"<" '{print $1}')-${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}
    - echo $ver
    - ls app
    - echo "$DOCKER_LOGIN"
    - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY_HOST --username $DOCKER_LOGIN --password-stdin
    - docker build  --build-arg app_version=${DOCKER_IMAGE_TAG}:$ver --build-arg app_compilation_date=`date -u +"%Y-%m-%dT%H:%M:%SZ"` -t $DOCKER_REGISTRY_HOST/${DOCKER_IMAGE_TAG}:$ver .
    - docker push $DOCKER_REGISTRY_HOST/${DOCKER_IMAGE_TAG}:$ver
  image: docker:latest
  only:
    - test

publish-dev:
  stage: publish
  services:
    - docker:19.03.0-dind
  script:
    - cd ${BUILD_FOLDER}
    - projectfile=${BUILD_FOLDER}
    - ver=$(cat $projectfile.csproj | grep '<Version>' | awk -F ">" '{print $2}' | awk -F"<" '{print $1}')-${CI_COMMIT_REF_NAME}
    - echo $ver
    - ls app
    - echo "$DOCKER_LOGIN"
    - echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY_HOST --username $DOCKER_LOGIN --password-stdin
    - docker build  --build-arg app_version=${DOCKER_IMAGE_TAG}:$ver --build-arg app_compilation_date=`date -u +"%Y-%m-%dT%H:%M:%SZ"` -t $DOCKER_REGISTRY_HOST/${DOCKER_IMAGE_TAG}:$ver .
    - docker push $DOCKER_REGISTRY_HOST/${DOCKER_IMAGE_TAG}:$ver
  image: docker:latest
  only:
    - develop